# start with base image
FROM mysql:5.6.39
# import data into conainer
# All scripts in docker-entrypoint-initdb.d/ are automatically executed during container startup
# COPY ./db/dlt4edu-service.sql /docker-entrypoint-initdb.d/
